spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.102
    port: 6379
    password:
#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: 127.0.0.1
#    port: 6379
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

#wechat:
#  # 公众账号, 授权
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret:
#
#  # 开放平台,  卖家扫码登录用
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx
#
#  # 支付/商户号
#  mchId: 1483469312
#  mchKey: 06C56A89949D617xxxxxxxxxxx
#  # 发起支付不需要证书, 退款需要
#  keyPath:
#  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
#  templateId:
#    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
#
#projectUrl:
#  wechatMpAuthorize: http://lsx888.natapp1.cc
#  wechatOpenAuthorize: http://lsx888.natapp1.cc
#  sell: http://lsx888.natapp1.cc
#logging:
#  level:
#    com.imooc.dataobject.mapper: trace
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#
## 又拍云服务 见 https://console.upyun.com/services/file/
#upyun:
#  bucketName: XXX
#  userName: xxx
#  password: xxxx
#  imageHost: http://xxx.com/
#server:
#  servlet:
server:
  context-path: /sell
#  wx0a7719ed997b8977
wechat:
  #公众帐号，授权
  mpAppId: wx0a7719ed997b8977
  mpAppSecret: 4aa3ef4ff73444a7b9ac8acbc5baaa18

  # 开放平台,  卖家扫码登录用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

  # 支付/商户号
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  # 发起支付不需要证书, 退款需要
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://yrc.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: WQ2n3Z7X_ttr9-BEauINn5CiTuDDV7AyGynU6f9ZIgk
projectUrl:
  wechatMpAuthorize: http://yrc.natapp1.cc
  wechatOpenAuthorize: http://yrc.natapp1.cc
  sell: http://yrc.natapp1.cc

logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
